### ISSUE TITLE
feat: Support for .json files

### ISSUE THREAD

**Issue by Bentheminernz** [izyuumi/xcode-discord-rpc#4]
### Prerequisites

- [x] I have searched for [existing issues](https://github.com/izyumidev/xcode-discord-rpc/issues) that already include this feature request, without success.

### Describe the Feature Request

Can you add support for .json files for Discord RPC?

### Describe the Use Case

Shows .json files on the RPC

**Comment by izyuumi** [comment]
Thanks for the issue! It's implemented now in [v0.1.8](https://github.com/izyuumi/xcode-discord-rpc/releases/tag/v0.1.8). I will close this issue, but let me know if there's anything else you would want to see.
![CleanShot 20240708 074849@2x](https://github.com/izyuumi/xcode-discord-rpc/assets/36561306/3ddbd46d-5fae-4d97-a487-6db86a69ab8e)
