### ISSUE TITLE
bug: not opening on Intel Mac

### ISSUE THREAD

**Issue by kilianbalaguer** [izyuumi/xcode-discord-rpc#7]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/izyumidev/xcode-discord-rpc/issues) that already report this problem, without success.

### Version

latest

### Current Behavior

when I start the app it does nothing not showing status I have Intel Mac

### Expected Behavior

show Xcode status

### Steps to Reproduce

run command to start the app

**Comment by izyuumi** [comment]
What command are you using to run the app?

**Comment by kilianbalaguer** [comment]
@izyuumi 
brew tap izyumidev/xcode-discord-rpc
brew install xcode-discord-rpc
brew services restart xcode-discord-rpc

**Comment by kilianbalaguer** [comment]
@izyuumi is this apple silicone only?

**Comment by izyuumi** [comment]
@kilianbalaguer I did not intend to make it Apple Silicon only. However, it is true that I do not own an Intel-based Mac device to test this with. It would be greatly appreciated if you could help me make it work on non-Apple Silicon devices.

**Comment by izyuumi** [comment]
If you could help, could you run `brew services list`? Do you see `xcode-discord-rpc` in the list marked `started`?

**Comment by kilianbalaguer** [comment]
@izyuumi sure I could help with that and yes I will try that command to see if its even runnning
one sec.

**Comment by kilianbalaguer** [comment]
<img width="1136" alt="Scherm­afbeelding 2024-12-20 om 11 07 47" src="https://github.com/user-attachments/assets/20dc876a-8fc4-4a2a-9247-83ebc65aa4fc" />
here I got this when checking

**Comment by kilianbalaguer** [comment]
<img width="697" alt="Scherm­afbeelding 2024-12-20 om 11 10 17" src="https://github.com/user-attachments/assets/ce81213e-cd8c-477b-8dae-85427870e4a7" />
it might be a wrong CPU option in the project are you sure its set to not only apple silicon I could do it if you want if Ik where to get the source and what to use for it

**Comment by kilianbalaguer** [comment]
I just check you builded it to apple silicon tho it might be compatible with intel too
@izyuumi

**Comment by kilianbalaguer** [comment]
@izyuumi I'm almost done fixing it I am going to test it after words and see if it works

**Comment by kilianbalaguer** [comment]
@izyuumi it works I did it now I need to make it universal so that its one file that's works on silicon and intel

**Comment by kilianbalaguer** [comment]
@izyuumi now it does start but only the problem is that it does not ask for the permissions like automatization and stuff so its running but not showing on discord what?

**Comment by kilianbalaguer** [comment]
NEVER MIND IT WORKS OMG

**Comment by kilianbalaguer** [comment]
i will make it cross cpu type later today

**Comment by izyuumi** [comment]
Sorry for the late reply, and thank you for figuring it out!

**Comment by royalgraphx** [comment]
Just ran into the same issue as this is the first Xcode RPC to appear in Google, @kilianbalaguer have you made a fork or a pull request yet? This is a very easy fix, as you've already noticed, the binary is ARM only.

**Comment by izyuumi** [comment]
@kilianbalaguer The new update has been released, and you should be able to run the app on an Inten Mac. Thank you for making this issue! Let me know if you need anything else :)

**Comment by kilianbalaguer** [comment]
Okay sorry i was very bussy had so much work going on
